# Generated by Django 5.0 on 2024-12-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_detection_residue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(null=True, upload_to='frames/')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and time of detection')),
                ('most_confident_label', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Captura',
                'verbose_name_plural': 'Capturas',
            },
        ),
        migrations.DeleteModel(
            name='Residue',
        ),
        migrations.DeleteModel(
            name='TrashCan',
        ),
    ]
