# Generated by Django 5.0 on 2024-12-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_capture_delete_residue_delete_trashcan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='most_confident_label',
        ),
        migrations.AddField(
            model_name='capture',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capture',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capture',
            name='placa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
