# Generated by Django 5.0 on 2024-12-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_capture_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
